/* jshint rhino:true, unused: false */
/* jscs:disable validateIndentation */
/*global name:true, less, loadStyleSheet, os */

var less = global.less = require('../less')();

less.ImportManager = require('../less/import-manager')(less.environment);
less.PluginLoader = require('./plugin-loader');
less.PluginManager = require('../less/plugin-manager');
less.modules = {
    path: require('path')
};

// NOTE: attemp to integrate auto-prefixer plugin failed because it is too heavy for Rhino 
//       - size is 2MB in browserified form and resulting JS fails to load into Rhino
//       with the error "generated bytecode for method exceeds 64K limit"
// less.LessPluginAutoPrefixer = require('less-plugin-autoprefix');
